spring:
  cloud:
    stream:
      defaultBinder: 'kafka'
      kafka:
        binder:
          brokers: localhost:9092
          replication-factor: 1
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
#          producer:
#            headerMode: embeddedHeaders
          destination: greetings
          contentType: application/json
  zipkin:
    baseUrl: http://localhost:9411
    enabled: true
    encoder: json-v1
    sender:
      type: web

  main:
    allow-bean-definition-overriding: true